### ISSUE TITLE
Pi3 error stating

### ISSUE THREAD

**Issue by suxfuuu** [whiteShtef/PiRadio#1]
I already have installed the mpg123 but i keep getting this error, sadly i don't know anything about coding .

root@raspberrypi:/home/pi/Downloads/PiRadio-master/PiRadio# python3 PiRadio.py
Loading - this may take a couple of seconds.
Traceback (most recent call last):
  File "PiRadio.py", line 38, in <module>
    install_package_by_apt("mpg123")
NameError: name 'install_package_by_apt' is not defined

**Comment by sbrki** [comment]
It was a simple typo, 
thank you for reporting this.
