### ISSUE TITLE
new issue starting pi3

### ISSUE THREAD

**Issue by suxfuuu** [whiteShtef/PiRadio#2]
Thx for your fast reply, but now i'm getting this:
I'm doing something wrong?

root@raspberrypi:/home/pi/Downloads/PiRadio-master/PiRadio# python3 PiRadio.py 
Loading - this may take a couple of seconds.
Package 'mpg123' is already installed on this pi.
Traceback (most recent call last):
  File "PiRadio.py", line 56, in <module>
    PiFMprocess = subprocess.Popen(["./pifm","-",BROADCAST_FREQUENCY,"48000", "stereo"], stdin=music_pipe_r, stdout=dev_null)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

**Comment by sbrki** [comment]
yes, you are not running the script as **root**.
Run `sudo python3 PiRadio.py`.
It also explicitly says that in the step 4 in [Readme.](https://github.com/whiteShtef/PiRadio/blob/master/README.md)

**Comment by suxfuuu** [comment]
yes i'm running as root  **root@raspberrypi**:/home/pi/Downloads/PiRadio-master/PiRadio# python3 PiRadio.py

anyway

pi@raspberrypi:~/Downloads/PiRadio-master/PiRadio $ sudo python3 PiRadio.py
Loading - this may take a couple of seconds.
Package 'mpg123' is already installed on this pi.
Traceback (most recent call last):
  File "PiRadio.py", line 56, in <module>
    PiFMprocess = subprocess.Popen(["./pifm","-",BROADCAST_FREQUENCY,"48000", "stereo"], stdin=music_pipe_r, stdout=dev_null)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
pi@raspberrypi:~/Downloads/PiRadio-master/PiRadio $
